apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  replicas: {{ default 0 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
    spec:
      {{ if .Values.serviceAccount }}serviceAccount: {{ .Values.serviceAccount }}{{ end }}
      {{ if .Values.serviceAccountName }}serviceAccountName: {{ .Values.serviceAccountName }}{{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        {{ if .Values.env }}
        env:
{{ toYaml .Values.env | indent 10 }}
        {{ end }}
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        livenessProbe:
          httpGet:
            path: {{ default "/" .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.service.internalPort | int }}
        readinessProbe:
          httpGet:
            path: {{ default "/" .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.service.internalPort | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}