apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-deploy
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        env:
{{ toYaml .Values.env | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path | default / }}
            port: {{ .Values.service.internalPort | int }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path | default / }}
            port: {{ .Values.service.internalPort | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}